export const iconMap = {
  "01d": "src/assets/iconeMeteo/sunny.png",
  "01n": "src/assets/iconeMeteo/clear-night.png",
  "02d": "src/assets/iconeMeteo/partly-cloudy.png",
  "02n": "src/assets/iconeMeteo/partly-cloudy-night.png",
  "03d": "src/assets/iconeMeteo/cloudy.png",
  "03n": "src/assets/iconeMeteo/cloudy.png",
  "04d": "src/assets/iconeMeteo/overcast.png",
  "04n": "src/assets/iconeMeteo/overcast.png",
  "09d": "src/assets/iconeMeteo/showers.png",
  "09n": "src/assets/iconeMeteo/showers.png",
  "10d": "src/assets/iconeMeteo/rain.png",
  "10n": "src/assets/iconeMeteo/rain.png",
  "11d": "src/assets/iconeMeteo/thunderstorm.png",
  "11n": "src/assets/iconeMeteo/thunderstorm.png",
  "13d": "src/assets/iconeMeteo/snow.png",
  "13n": "src/assets/iconeMeteo/snow.png",
  "50d": "src/assets/iconeMeteo/fog.png",
  "50n": "src/assets/iconeMeteo/fog-night.png",
};
